spring:
    application:
        name: Personal-Task-Manager
    datasource:
        url: jdbc:h2:mem:taskdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driverClassName: org.h2.Driver
        username: sa
        password: password
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create-drop
        naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                use_sql_comments: true
                generate_statistics: false
        defer-datasource-initialization: true
    sql:
        init:
            mode: always
            data-locations: classpath:data.sql
            continue-on-error: false
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                web-allow-others: false
    thymeleaf:
        cache: false
        prefix: classpath:/templates/
        suffix: .html
        encoding: UTF-8
        mode: HTML
        check-template-location: true
server:
    port: 8080
    servlet:
        context-path: /
    error:
        include-message: always
        include-binding-errors: always
logging:
    level:
        com.personaltaskmanager: DEBUG
        org.springframework.web: INFO
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
        org.springframework.security: DEBUG
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
app:
    task:
        default-priority: MEDIUM
        max-description-length: 500
        date-format: "yyyy-MM-dd'T'HH:mm"
    category:
        default-color: "#007bff"
        max-name-length: 50